# fly.toml app configuration file generated for wandering-fog-1322 on 2023-05-28T17:57:24+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wandering-fog-1322"
primary_region = "arn"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
